// <auto-generated />
using System;
using System.Collections.Generic;
using Fushi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fushi.Infrastructure.Persistence.Migrations;

[DbContext(typeof(FushiDbContext))]
partial class FushiDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260808174520_InitialCreate";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Fushi.Core.Entities.Audits.AuditEntry", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int>("Action")
                    .HasColumnType("integer")
                    .HasColumnName("action");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at");

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("created_by");

                b.Property<long>("GuildId")
                    .HasColumnType("bigint")
                    .HasColumnName("guild_id");

                b.Property<string>("Metadata")
                    .HasColumnType("jsonb")
                    .HasColumnName("metadata");

                b.Property<string>("Reason")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("reason");

                b.Property<int>("Scope")
                    .HasColumnType("integer")
                    .HasColumnName("scope");

                b.Property<string>("SubjectCode")
                    .HasMaxLength(6)
                    .HasColumnType("character varying(6)")
                    .HasColumnName("subject_code");

                b.Property<Guid?>("SubjectId")
                    .HasColumnType("uuid")
                    .HasColumnName("subject_id");

                b.Property<long?>("TargetId")
                    .HasColumnType("bigint")
                    .HasColumnName("target_id");

                b.HasKey("Id")
                    .HasName("pk_audit_entries");

                b.HasIndex("GuildId", "CreatedAt")
                    .IsDescending(false, true)
                    .HasDatabaseName("ix_audit_entries_guild_created");

                b.HasIndex("GuildId", "SubjectCode")
                    .HasDatabaseName("ix_audit_entries_guild_subject_code");

                b.HasIndex("GuildId", "Scope", "CreatedAt")
                    .IsDescending(false, false, true)
                    .HasDatabaseName("ix_audit_entries_guild_scope_created");

                b.ToTable("audit_entries");
            });

        modelBuilder.Entity("Fushi.Core.Entities.Cycles.Cycle", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<long?>("AnnouncementMessageId")
                    .HasColumnType("bigint")
                    .HasColumnName("announcement_message_id");

                b.Property<DateTimeOffset>("ClosesAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("closes_at");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(6)
                    .HasColumnType("character(6)")
                    .HasColumnName("code")
                    .IsFixedLength();

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at");

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("created_by");

                b.Property<DateTimeOffset?>("DeletedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("deleted_at");

                b.Property<long?>("DeletedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("deleted_by");

                b.Property<long>("GuildId")
                    .HasColumnType("bigint")
                    .HasColumnName("guild_id");

                b.Property<DateTimeOffset>("OpensAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("opens_at");

                b.Property<long?>("ResultsMessageId")
                    .HasColumnType("bigint")
                    .HasColumnName("results_message_id");

                b.Property<DateOnly>("ScheduledDate")
                    .HasColumnType("date")
                    .HasColumnName("scheduled_date");

                b.Property<int>("Status")
                    .HasColumnType("integer")
                    .HasColumnName("status");

                b.Property<DateTimeOffset?>("UpdatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("updated_at");

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("updated_by");

                b.ComplexProperty(typeof(Dictionary<string, object>), "Policy", "Fushi.Core.Entities.Cycles.Cycle.Policy#VotingPolicy", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<bool>("AllowAbstain")
                            .HasColumnType("boolean")
                            .HasColumnName("allow_abstain");

                        b1.Property<bool>("AllowSelfVote")
                            .HasColumnType("boolean")
                            .HasColumnName("allow_self_vote");

                        b1.Property<bool>("AllowVoteChange")
                            .HasColumnType("boolean")
                            .HasColumnName("allow_vote_change");

                        b1.Property<double>("ApprovalRatio")
                            .HasColumnType("double precision")
                            .HasColumnName("approval_ratio");

                        b1.Property<int>("Quorum")
                            .HasColumnType("integer")
                            .HasColumnName("quorum");
                    });

                b.HasKey("Id")
                    .HasName("pk_cycles");

                b.HasIndex("GuildId")
                    .IsUnique()
                    .HasDatabaseName("ix_cycles_one_open_per_guild")
                    .HasFilter("status = 1 AND deleted_at IS NULL");

                b.HasIndex("GuildId", "Code")
                    .IsUnique()
                    .HasDatabaseName("ix_cycles_guild_code");

                b.HasIndex("GuildId", "ScheduledDate")
                    .IsUnique()
                    .HasDatabaseName("ix_cycles_guild_date")
                    .HasFilter("deleted_at IS NULL");

                b.ToTable("cycles");
            });

        modelBuilder.Entity("Fushi.Core.Entities.Guilds.Guild", b =>
            {
                b.Property<long>("Id")
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at");

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("created_by");

                b.Property<DateTimeOffset?>("DeletedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("deleted_at");

                b.Property<long?>("DeletedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("deleted_by");

                b.Property<bool>("IsEnabled")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(false)
                    .HasColumnName("is_enabled");

                b.Property<DateTimeOffset?>("UpdatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("updated_at");

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("updated_by");

                b.ComplexProperty(typeof(Dictionary<string, object>), "Channels", "Fushi.Core.Entities.Guilds.Guild.Channels#GuildChannels", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<long?>("ArchiveChannelId")
                            .HasColumnType("bigint")
                            .HasColumnName("archive_channel_id");

                        b1.Property<long?>("IntakeChannelId")
                            .HasColumnType("bigint")
                            .HasColumnName("intake_channel_id");

                        b1.Property<long?>("LogChannelId")
                            .HasColumnType("bigint")
                            .HasColumnName("log_channel_id");

                        b1.Property<long?>("ResultsChannelId")
                            .HasColumnType("bigint")
                            .HasColumnName("results_channel_id");

                        b1.Property<long?>("ReviewChannelId")
                            .HasColumnType("bigint")
                            .HasColumnName("review_channel_id");
                    });

                b.ComplexProperty(typeof(Dictionary<string, object>), "Policy", "Fushi.Core.Entities.Guilds.Guild.Policy#VotingPolicy", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<bool>("AllowAbstain")
                            .HasColumnType("boolean")
                            .HasColumnName("allow_abstain");

                        b1.Property<bool>("AllowSelfVote")
                            .HasColumnType("boolean")
                            .HasColumnName("allow_self_vote");

                        b1.Property<bool>("AllowVoteChange")
                            .HasColumnType("boolean")
                            .HasColumnName("allow_vote_change");

                        b1.Property<double>("ApprovalRatio")
                            .HasColumnType("double precision")
                            .HasColumnName("approval_ratio");

                        b1.Property<int>("Quorum")
                            .HasColumnType("integer")
                            .HasColumnName("quorum");
                    });

                b.ComplexProperty(typeof(Dictionary<string, object>), "Schedule", "Fushi.Core.Entities.Guilds.Guild.Schedule#CycleSchedule", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<TimeOnly>("ClosesAt")
                            .HasColumnType("time without time zone")
                            .HasColumnName("closes_at");

                        b1.Property<int>("Days")
                            .HasColumnType("integer")
                            .HasColumnName("cycle_days");

                        b1.Property<TimeOnly>("OpensAt")
                            .HasColumnType("time without time zone")
                            .HasColumnName("opens_at");

                        b1.Property<string>("TimeZoneId")
                            .IsRequired()
                            .HasMaxLength(64)
                            .HasColumnType("character varying(64)")
                            .HasColumnName("time_zone_id");
                    });

                b.HasKey("Id")
                    .HasName("pk_guilds");

                b.ToTable("guilds");
            });

        modelBuilder.Entity("Fushi.Core.Entities.Guilds.VotingPermission", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at");

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("created_by");

                b.Property<DateTimeOffset?>("DeletedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("deleted_at");

                b.Property<long?>("DeletedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("deleted_by");

                b.Property<long>("GuildId")
                    .HasColumnType("bigint")
                    .HasColumnName("guild_id");

                b.Property<string>("Note")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("note");

                b.Property<int>("Scope")
                    .HasColumnType("integer")
                    .HasColumnName("scope");

                b.Property<long>("TargetId")
                    .HasColumnType("bigint")
                    .HasColumnName("target_id");

                b.Property<DateTimeOffset?>("UpdatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("updated_at");

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("updated_by");

                b.HasKey("Id")
                    .HasName("pk_voting_permissions");

                b.HasIndex("GuildId", "Scope", "TargetId")
                    .IsUnique()
                    .HasDatabaseName("ix_voting_permissions_guild_target_live")
                    .HasFilter("deleted_at IS NULL");

                b.ToTable("voting_permissions");
            });

        modelBuilder.Entity("Fushi.Core.Entities.Submissions.Submission", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<long>("ApplicantId")
                    .HasColumnType("bigint")
                    .HasColumnName("applicant_id");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(6)
                    .HasColumnType("character(6)")
                    .HasColumnName("code")
                    .IsFixedLength();

                b.Property<string>("Content")
                    .IsRequired()
                    .HasMaxLength(3800)
                    .HasColumnType("character varying(3800)")
                    .HasColumnName("content");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at");

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("created_by");

                b.Property<Guid?>("CycleId")
                    .HasColumnType("uuid")
                    .HasColumnName("cycle_id");

                b.Property<DateTimeOffset?>("DecidedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("decided_at");

                b.Property<long?>("DecidedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("decided_by");

                b.Property<DateTimeOffset?>("DeletedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("deleted_at");

                b.Property<long?>("DeletedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("deleted_by");

                b.Property<long>("GuildId")
                    .HasColumnType("bigint")
                    .HasColumnName("guild_id");

                b.Property<int?>("Outcome")
                    .HasColumnType("integer")
                    .HasColumnName("outcome");

                b.Property<long?>("ReviewMessageId")
                    .HasColumnType("bigint")
                    .HasColumnName("review_message_id");

                b.Property<long>("SourceChannelId")
                    .HasColumnType("bigint")
                    .HasColumnName("source_channel_id");

                b.Property<long>("SourceMessageId")
                    .HasColumnType("bigint")
                    .HasColumnName("source_message_id");

                b.Property<int>("Status")
                    .HasColumnType("integer")
                    .HasColumnName("status");

                b.Property<long?>("ThreadId")
                    .HasColumnType("bigint")
                    .HasColumnName("thread_id");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("title");

                b.Property<DateTimeOffset?>("UpdatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("updated_at");

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("updated_by");

                b.HasKey("Id")
                    .HasName("pk_submissions");

                b.HasIndex("CycleId")
                    .HasDatabaseName("ix_submissions_cycle");

                b.HasIndex("GuildId", "Code")
                    .IsUnique()
                    .HasDatabaseName("ix_submissions_guild_code");

                b.HasIndex("GuildId", "SourceMessageId")
                    .IsUnique()
                    .HasDatabaseName("ix_submissions_guild_source_message");

                b.HasIndex("GuildId", "Status", "CreatedAt")
                    .HasDatabaseName("ix_submissions_guild_status_created");

                b.ToTable("submissions");
            });

        modelBuilder.Entity("Fushi.Core.Entities.Submissions.Vote", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int>("Choice")
                    .HasColumnType("integer")
                    .HasColumnName("choice");

                b.Property<string>("Comment")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("comment");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at");

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("created_by");

                b.Property<DateTimeOffset?>("DeletedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("deleted_at");

                b.Property<long?>("DeletedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("deleted_by");

                b.Property<int>("RevisionCount")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(0)
                    .HasColumnName("revision_count");

                b.Property<Guid>("SubmissionId")
                    .HasColumnType("uuid")
                    .HasColumnName("submission_id");

                b.Property<DateTimeOffset?>("UpdatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("updated_at");

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint")
                    .HasColumnName("updated_by");

                b.Property<long>("VoterId")
                    .HasColumnType("bigint")
                    .HasColumnName("voter_id");

                b.HasKey("Id")
                    .HasName("pk_votes");

                b.HasIndex("SubmissionId", "VoterId")
                    .IsUnique()
                    .HasDatabaseName("ix_votes_submission_voter_live")
                    .HasFilter("deleted_at IS NULL");

                b.ToTable("votes");
            });

        modelBuilder.Entity("Fushi.Core.Entities.Guilds.VotingPermission", b =>
            {
                b.HasOne("Fushi.Core.Entities.Guilds.Guild", null)
                    .WithMany("VotingPermissions")
                    .HasForeignKey("GuildId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_voting_permissions_guilds_guild_id");
            });

        modelBuilder.Entity("Fushi.Core.Entities.Submissions.Submission", b =>
            {
                b.HasOne("Fushi.Core.Entities.Cycles.Cycle", null)
                    .WithMany("Submissions")
                    .HasForeignKey("CycleId")
                    .OnDelete(DeleteBehavior.SetNull)
                    .HasConstraintName("fk_submissions_cycles_cycle_id");
            });

        modelBuilder.Entity("Fushi.Core.Entities.Submissions.Vote", b =>
            {
                b.HasOne("Fushi.Core.Entities.Submissions.Submission", null)
                    .WithMany("Votes")
                    .HasForeignKey("SubmissionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_votes_submissions_submission_id");
            });

        modelBuilder.Entity("Fushi.Core.Entities.Cycles.Cycle", b =>
            {
                b.Navigation("Submissions");
            });

        modelBuilder.Entity("Fushi.Core.Entities.Guilds.Guild", b =>
            {
                b.Navigation("VotingPermissions");
            });

        modelBuilder.Entity("Fushi.Core.Entities.Submissions.Submission", b =>
            {
                b.Navigation("Votes");
            });
#pragma warning restore 612, 618
    }
}
